version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - run:
          name: Install dependencies
          command: |
            curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
            chmod a+rx /usr/local/bin/youtube-dl
      - checkout
      - run:
          name: Restore package dependencies
          command: |
            dotnet restore
      - run:
          name: Run unit tests
          working_directory: test/NYoutubeDL.Tests
          command: |
            dotnet test
      - run:
          name: Package release
          working_directory: src/NYoutubeDL
          command: |
            dotnet build -c Release
            dotnet pack -c Release
      - store_artifacts:
          path: src/NYoutubeDL/bin/Release